Fix null_terminated crate's utf dependency version
The build currently fails as follows:

  error[E0658]: use of unstable library feature 'proc_macro_is_available'
    --> /home/penberg/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.33/src/detection.rs:28:21
     |
  28 |     let available = proc_macro::is_available();
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #71436 <https://github.com/rust-lang/rust/issues/71436> for more information
     = help: add `#![feature(proc_macro_is_available)]` to the crate attributes to enable

  For more information about this error, try `rustc --explain E0658`.
  error: could not compile `proc-macro2` due to previous error

The problem is that the "null_terminated" crate depends on the "utf"
with a relaxed "0.1" version, which causes cargo to pull a version that
is incompatible with our toolchain.

Fix up the dependency by relying on the old "0.1.5" version explicitly.